### ISSUE TITLE
Cannot install the package

### ISSUE THREAD

**Issue by settermjd** [Mogztter/antora-site-generator-lunr#1]
When I following the install instructions, I receive the following error:

```
npm ERR! code E404
npm ERR! 404 Not Found: antora-site-generator-lunr@latest
```

Can you suggest a fix please?

**Comment by Mogztter** [comment]
Hello @settermjd,

This package is not yet published on npmjs that why `npm install` can't find it.
I will create and publish a version to https://www.npmjs.com/ in the next few days.

In the meantime, you can manually edit the default pipeline as described here: https://github.com/Mogztter/antora-lunr

In my opinion, Lunr should be an add-on that can be unable in a pipeline (instead of duplicating the default pipeline). But that's not how Antora pipeline is working right now.

**Comment by wols** [comment]
'antora-site-generator-lunr@latest' is not in the npm registry.
You should bug the author to publish it (or use the name yourself!)

**Comment by Mogztter** [comment]
I've just published a version to npmjs: https://www.npmjs.com/package/antora-site-generator-lunr
This version is based on Antora 2.0.0.
