### ISSUE TITLE
Possible limit to number of pages lunr can process

### ISSUE THREAD

**Issue by roganjoshua** [Mogztter/antora-site-generator-lunr#83]
Hi I am building an antora site with perhaps > 1100 pages.

Not sure if this is helpful or if I really am pushing it all tar too far.
```
  <--- Last few GCs --->
  
  [4648:00000155E7153AC0]   251886 ms: Scavenge 2044.0 (2052.1) -> 2043.3 (2053.1) MB, 20.8 / 0.0 ms  (average mu = 0.229, current mu = 0.189) allocation failure 
  [4648:00000155E7153AC0]   255746 ms: Mark-sweep (reduce) 2044.8 (2057.1) -> 2043.8 (2058.3) MB, 3848.7 / 0.0 ms  (+ 0.1 ms in 23 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 3859 ms) (average mu = 0.175, current mu = 

FATAL warning : Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

 1: 00007FF74AD41DDF napi_wrap+109135
   2: 00007FF74ACE6D06 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet,1>::NumberOfElementsOffset+33350
   3: 00007FF74ACE7AD6 node::OnFatalError+294
   4: 00007FF74B5B64CE v8::Isolate::ReportExternalAllocationLimitReached+94
   5: 00007FF74B59B31D v8::SharedArrayBuffer::Externalize+781
   6: 00007FF74B44574C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
   7: 00007FF74B450AAA v8::internal::Heap::ProtectUnprotectedMemoryChunks+1258
   8: 00007FF74B44DC59 v8::internal::Heap::PageFlagsAreConsistent+2457
   9: 00007FF74B4427F1 v8::internal::Heap::CollectGarbage+2033
  10: 00007FF74B4409F5 v8::internal::Heap::AllocateExternalBackingStore+1365
  11: 00007FF74B460F17 v8::internal::Factory::NewFillerObject+183
  12: 00007FF74B18E731 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1409
  13: 00007FF74B63F01D v8::internal::SetupIsolateDelegate::SetupHeap+463949
  14: 00007FF74B63FF97 v8::internal::SetupIsolateDelegate::SetupHeap+467911
  15: 000002CF2A9366B8 
```

**Comment by Mogztter** [comment]
@roganjoshua Could you please provide a heapdump?

With Node.js >= 12, you can use the `--heapsnapshot-signal=SIGUSR2` option:

```
$ node --heapsnapshot-signal=SIGUSR2 index.js &
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
node         1  5.5  6.1 787252 247004 ?       Ssl  16:43   0:02 node --heapsnapshot-signal=SIGUSR2 index.js
$ kill -USR2 1
$ ls
Heap.20190718.133405.15554.0.001.heapsnapshot
```

You should wait a bit until the memory is high enough. You can also use the `--max-old-space-size=4000` option to increase the memory limit.

Thanks

**Comment by roganjoshua** [comment]
Thanks I will try this although I am running it on windows :(

**Comment by roganjoshua** [comment]
--max-old-space-size=4000 is this option passed in on the antora command line

`antora --max-old-space=4000 site.yml`

**Comment by Mogztter** [comment]
No it's a Node.js option, you can use the environment variable `NODE_OPTIONS='--max-old-space-size=4096'`. 

Indeed, `heapsnapshot-signal` option is UNIX only. You can try using this option instead: https://github.com/nodejs/node/blob/master/doc/api/cli.md#--heapsnapshot-near-heap-limitmax_count

In theory, it will produce a heapdump when the heap is near the limit.

**Comment by roganjoshua** [comment]
I am sorry I don't know how to pass the heapsnapshot-near-heap-limitmax_count to node via antora

**Comment by Mogztter** [comment]
@roganjoshua I think it should work if you add it to the `NODE_OPTIONS` environment variable:


```
NODE_OPTIONS='--max-old-space-size=4096 --heapsnapshot-near-heap-limit=1' antora site.yml
```

**Comment by roganjoshua** [comment]
K I managed to get a dump!! 

[Heap.20201126.142123.5699.0.001.heapsnapshot.zip](https://github.com/Mogztter/antora-site-generator-lunr/files/5603531/Heap.20201126.142123.5699.0.001.heapsnapshot.zip)

**Comment by Mogztter** [comment]
@roganjoshua Nice! Could you do exactly the same but using the default pipeline? The heapdump is relatively small, only 266Mb.

I can see some relatively big images associated to the content catalog:

![file-image](https://user-images.githubusercontent.com/333276/100367139-0fea1900-3002-11eb-99de-06377554bfca.png)

![contentcatalog](https://user-images.githubusercontent.com/333276/100367136-0eb8ec00-3002-11eb-9084-7a0c17ee033b.png)

I also notice a few "Node" object that seems related to cheerio. But since they are a lot of them I wonder if they are correctly GCed, maybe we are keeping a reference somewhere.

Anyway the second heapdump would be helpful to compare.

Thanks!

**Comment by roganjoshua** [comment]
will do

**Comment by roganjoshua** [comment]
I don't get a dump without lunr but looking at the images I have been given they are huge!!! :/

**Comment by roganjoshua** [comment]
Some of the images are ~1Mb probably around 70Mb in total. Do you think this could be the issue?

**Comment by Mogztter** [comment]
> I don't get a dump without lunr but looking at the images I have been given they are huge!!! :/

You need to reduce the memory to get closer to the limit otherwise the "heapsnapshot-near-heap-limit" won't get triggered.

I'm also a bit surprised that you get a 250Mb heapdump with a 4Gb limit (using `--max-old-space-size=4096`). Could you please share the exact command you are running?

In short, if you don't get a heapdump with the default pipeline try to reduce the max memory. For instance, you could try with 1Gb or 512Mb using respectively `--max-old-space-size=1024` and `--max-old-space-size=512`. If you don't get a heapdump try to reduce further.

> Some of the images are ~1Mb probably around 70Mb in total. Do you think this could be the issue?

In theory, large images should not affect Antora Lunr because we only care about text (i.e. pages not assets). But you might be close to the memory limit with the default pipeline and Antora Lunr tips the balance.
It's worth noting that Antora Lunr has a linear memory consumption (if there's no memory leak of course). So the memory will grow linearly with the size of your content catalog (text only).

Let's take a concret example, you have a memory limit of 2Gb.
With the default pipeline you consume 1.5Gb but Antora Lunr requires 1Gb to create the index, you are now above the limit.

I think the questions we need to answer are:

- Is Antora Lunr has a memory leak?
- Is Antora Lunr consume an excessive amount of memory?
- Could Antora Lunr consume less memory?

For now, all I can see is that files associated to the content catalog (used in the default pipeline) takes 75% of the available memory.

**Comment by roganjoshua** [comment]
rm Heap*
marty@LV4-PF1DZY5K:~/help$ DOCSEARCH_ENABLED='true' DOCSEARCH_ENGINE='true'  node --max-old-space-size=210 --heapsnapshot-near-heap-limit=1  /home/marty/.nvm/versions/node/v14.14.0/bin/antora --stacktrace --ui-bundle-url ~/help/ui-bundle.zip --to-dir ~/publish site.yml --generator antora-site-generator-lunr
asciidoctor: WARNING: skipping reference to missing attribute: 1-n
asciidoctor: WARNING: skipping reference to missing attribute: 1-n
asciidoctor: WARNING: skipping reference to missing attribute: 1-n
asciidoctor: WARNING: skipping reference to missing attribute: 1-n
asciidoctor: WARNING: skipping reference to missing attribute: 0-9
asciidoctor: WARNING: skipping reference to missing attribute: 0
Wrote snapshot to /home/marty/help/Heap.20201201.114902.9999.0.001.heapsnapshot

<--- Last few GCs --->

[9999:0x5d299e0]    60991 ms: Mark-sweep 201.8 (213.1) -> 201.7 (213.1) MB, 130.4 / 0.0 ms  (average mu = 0.129, current mu = 0.000) heap profiler GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa63060 node::Abort() [node]
 2: 0x995c57 node::FatalError(char const*, char const*) [node]
 3: 0xc3bc1e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xc3bf97 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xe04a05  [node]
 6: 0xe055ac  [node]
 7: 0xe12f3b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xe15625 v8::internal::Heap::HandleGCRequest() [node]
 9: 0xdb8587 v8::internal::StackGuard::HandleInterrupts() [node]
10: 0x1131363 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x14c8359  [node]
Aborted


https://drive.google.com/file/d/1WXlFKaEYqzuuiDFU9FQekXCZkAVgJVPX/view?usp=sharing

**Comment by ggrossetie** [comment]
@roganjoshua We made a few changes in https://gitlab.com/antora/antora-lunr-extension. The new extension should consume much less memory, please give it a try.
