### ISSUE TITLE
using  antora-site-generator-lunr with Antora 3.0.0 (currently alpha)

### ISSUE THREAD

**Issue by ahus1** [Mogztter/antora-site-generator-lunr#95]
I did some experiments with Antora 3.0.0-alpha.7 and this site generator.

I was unable to make it work Antora 3.0.0-alpha.8+ due to API changes in Antora.

TL;DR: works after using some "force" - thanks for providing the plugin!

I needed to update the dependencies to use the 3.x version instead of 2.x using _resolutions_ (see [package.json](https://github.com/ahus1/intellij-asciidoc-plugin.ahus1.de/blob/main/package.json) here). 

NOTE: The "resolutions" functionality in package.json will work in yarn only.

This is just a note in case someone wants to try something similar.

**Comment by Mogztter** [comment]
Thanks for the heads-up! 👍🏻 

As soon as Antora 3.0.0 final is out, I will try to release a compatible version. As of today, v3.0.0-alpha.6 is out! https://gitlab.com/antora/antora/-/tree/v3.0.0-alpha.6

**Comment by ahus1** [comment]
I updated the issue's text above how it works with the latest version of this plugin and the latest version of Antora.

**Comment by mojavelinux** [comment]
The correct solution to this problem is to tell yarn or npm not to install optional dependencies. The site generator depends on Antora 2 as an optional dependency. If you are installing Antora 3 in addition to this generator, you're going to end up with a conflict. By telling yarn or npm to ignore optional dependencies, it will exclude Antora 2. No hacks required.

Here's how that looks with npm:

```
npm i --no-optional
```

Here's how that looks with yarn:

```
yarn --ignore-optional
```

Perhaps the README could be updated to offer this hint.

**Comment by ggrossetie** [comment]
I've updated the README to recommend to use the official extension: https://gitlab.com/antora/antora-lunr-extension

I don't think we should release a new version as the way forward is to use an extension rather than overriding the whole site generator.

**Comment by ahus1** [comment]
Thanks for taking care of the readme. With this update, this issue is resolved, therefore I close it.
